[versions]
gradle-starter = "0.94.0"
gradle-doctor = "0.12.1"
google-annotation = "1.9.1"
maven-threetenbp = "1.7.2"
maven-junit = "4.13.2"
maven-truth = "1.4.5"
maven-ticktock = "1.2.0-2021e"
maven-binarycompatiblity = "0.18.1"
maven-robolectric = "4.16"
maven-dokka = "2.1.0"
maven-vanniktech-maven-publish = "0.36.0"

[libraries]
starter-android = { module = "com.project.starter:android", version.ref = "gradle-starter" }
ticktock-compiler = { module = "dev.zacsweers.ticktock:ticktock-compiler", version.ref = "maven-ticktock" }
annotation-core = { module = "androidx.annotation:annotation", version.ref = "google-annotation" }
threetenbp-core = { module = "org.threeten:threetenbp", version.ref = "maven-threetenbp" }
junit-core = { module = "junit:junit", version.ref = "maven-junit" }
robolectric-core = { module = "org.robolectric:robolectric", version.ref = "maven-robolectric" }
truth-core = { module = "com.google.truth:truth", version.ref = "maven-truth" }
jetbrains-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "maven-dokka" }
vanniktech-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-vanniktech-maven-publish" }

[plugins]
starter-library-android = { id = "com.starter.library.android", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
ticktock = { id = "dev.zacsweers.ticktock", version.ref = "maven-ticktock" }
osacky-doctor = { id = "com.osacky.doctor", version.ref = "gradle-doctor" }
kotlinx-binarycompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "maven-binarycompatiblity" }
